#!/bin/bash

clear
echo -e "==================================================="
echo -e "#          Autoscript Mod By Vinstechmy           #"
echo -e "#-------------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit                 #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit          #"
echo -e "# For VPS with KVM and VMWare virtualization      #"
echo -e "# Build Up By Horasss                             #"
echo -e "# Modded By Vinstechmy                            #"
echo -e "#-------------------------------------------------#"
echo -e "# License To :                                    #"
echo -e "#-------------------------------------------------#"
echo -e "# Vinstechmy Premium Autoscript Lifetime          #"
echo -e "#                                                 #"
echo -e "# Thanks To : Horasss & Wildy-Project             #"
echo -e "#                                                 #"
echo -e "# This is Autoscript originally by Horas          #"
echo -e "# This script is not from the leak source         #"
echo -e "# I buy this Autoscript source from the developer #"
echo -e "# For education purpose only                      #"
echo -e "#                                                 #"
echo -e "# Thanks for using my Modded Autoscript           #"
echo -e "#                                                 #"
echo -e "# Telegram : t.me/vinstechmy                      #"
echo -e "# Whatsapp : wasap.my/601160938070                #"
echo -e "#-------------------------------------------------#"
echo -e "==================================================="
